name = "Tangle"
uuid = "324d6a3d-8d47-4281-bb16-2f63593471e6"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]
version = "0.1.0"

[deps]
CubicSplines = "9c784101-8907-5a6d-9be6-98f00873c89b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
MeshIO = "0.4"
julia = "1.9"

[extras]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "IterTools"]
