name = "Tangle"
uuid = "324d6a3d-8d47-4281-bb16-2f63593471e6"
version = "0.1.0"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]

[deps]
CubicSplines = "9c784101-8907-5a6d-9be6-98f00873c89b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Groebner = "0b43b601-686d-58a3-8a1c-6623616c7cd4"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
CubicSplines = "0.2"
DataStructures = "0.18"
GR = "0.72, 0.73"
GeometryBasics = "0.4.11"
Groebner = "0.10.2"
MeshIO = "0.4"
OrderedCollections = "1.8.1"
Plots = "1"
StaticArrays = "1"
SymbolicUtils = "3.32.0"
Symbolics = "6"
julia = "1.11"

[extras]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "IterTools"]
